<template>
	<!-- AI-built UI warning banner. Loud-but-not-broken (amber, not red).
	     Add this to the top of EVERY page Claude built so users + reviewers
	     know this surface hasn't been signed off by the UI/UX team yet. -->
	<div v-if="!hidden" class="overflow-hidden rounded-lg border-2 border-amber-400 bg-amber-50">
		<div class="flex items-start gap-3 px-4 py-3">
			<div class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-amber-200">
				<FeatherIcon name="alert-triangle" class="h-5 w-5 text-amber-800" />
			</div>
			<div class="min-w-0 flex-1">
				<div class="text-sm font-semibold text-amber-900">
					Built by Claude (AI) — pending UI/UX team review &amp; approval
				</div>
				<div class="mt-0.5 text-xs leading-relaxed text-amber-800">
					This page was generated by an AI agent and ships before the UI/UX team has reviewed it.
					<strong>Audit the diff before relying on this in production.</strong>
					Report visual / UX issues to the design team; report broken behaviour to the engineering team.
					<span v-if="commit" class="text-amber-700">
						· Last AI commit: <code class="rounded bg-amber-100 px-1 py-0.5 text-[10px] font-mono">{{ commit }}</code>
					</span>
				</div>
			</div>
			<button
				v-if="dismissible"
				type="button"
				class="shrink-0 text-amber-700 hover:text-amber-900"
				title="Hide for this session only — banner returns on next page load"
				@click="hidden = true"
			>
				<FeatherIcon name="x" class="h-4 w-4" />
			</button>
		</div>
	</div>
</template>

<script setup>
import { ref } from 'vue';
import { FeatherIcon } from 'frappe-ui';

defineProps({
	// Optional short git ref of the last AI commit on this page
	commit: { type: String, default: '' },
	// Allow per-session dismissal? Default true. Banner returns on next page load.
	dismissible: { type: Boolean, default: true },
});

const hidden = ref(false);
</script>
