---
- name: Setup ca public key to verify signed certificates
  block:
    - name: Setup certificate-authority key file from variable
      copy:
        content: "{{ ca_public_key }}"
        dest: /etc/ssh/ca.pub
      when: ca_public_key is defined and ca_public_key != ""

    - name: Download certificate-authority key file (fallback)
      get_url:
        url: "{{ ca_public_key_url | default('https://frappecloud.com/files/ca.pub') }}"
        dest: /etc/ssh/ca.pub
      when: ca_public_key is not defined or ca_public_key == ""
      ignore_errors: yes

    - name: Set key file permissions to 0644
      file:
        path: /etc/ssh/ca.pub
        owner: root
        group: root
        mode: 0644
      ignore_errors: yes

- name: Setup authorized principals for certificate authority
  block:
    - name: Create auth_principals directory
      file:
        path: /etc/ssh/auth_principals
        owner: root
        group: root
        state: directory

    - name: Set authorized principals for frappe
      copy:
        dest: /etc/ssh/auth_principals/frappe
        content: |
          all-servers
          {{ server | default(inventory_hostname) }}


    - name: Add certificate authority key location to sshd_config
      lineinfile:
        state: present
        path: /etc/ssh/sshd_config
        backup: yes
        line: "{{ item }}"
        insertafter: EOF
      with_items:
        - "TrustedUserCAKeys /etc/ssh/ca.pub"
        - "AuthorizedPrincipalsFile /etc/ssh/auth_principals/%u"

- name: Restart sshd service
  service:
    name: sshd
    state: reloaded
